### ISSUE TITLE
Ball of string doesnt work for me

### ISSUE THREAD

**Issue by st4nley29** [Builderb0y/BigGlobe#22] opened 2024-09-28 20:26 UTC
I treid to put strings to workbench with ball of string but at the end it consume my string and still display 0/0 under ball of string. Any ideas why that happen?

**Comment by Builderb0y** [comment] 2024-09-28 21:11
Looks like it's a bug affecting MC 1.20.4 and earlier. This will be fixed in the next version of Big Globe.

**Comment by Builderb0y** [comment] 2024-09-30 18:17
Should be fixed in V4.4.0.

**Comment by st4nley29** [comment] 2024-09-30 19:11
still same problem in v4.4.0 in 1.21.x

**Comment by st4nley29** [comment] 2024-09-30 19:14
![2024-09-30_21 12 42](https://github.com/user-attachments/assets/65e85355-cc6e-4507-ad8c-1e0f04072654)

**Comment by Builderb0y** [comment] 2024-09-30 19:24
Odd... it seems to be working fine for me in MC 1.21.1 with V4.4.0...

**Comment by st4nley29** [comment] 2024-10-01 20:14
maybe some mod is making an issue than

**Comment by Builderb0y** [comment] 2024-10-01 20:52
Possibly. I still need to try it outside a dev environment too. But if you can get it working with *only* big globe installed, that'll strongly imply that it's another mod breaking things. Also... is this issue on fabric? Or forge + sinytra connector?

**Comment by st4nley29** [comment] 2024-10-01 21:03
Im using fabric for that mod

**Comment by st4nley29** [comment] 2024-10-01 21:06
![2024-10-01_23 04 53](https://github.com/user-attachments/assets/a452cf83-a1eb-42db-9c9d-2401e53204f0)

**Comment by st4nley29** [comment] 2024-10-01 21:07
clear fabric 1.21 with Big Globe

**Comment by Builderb0y** [comment] 2024-10-01 21:55
Ok, finally managed to reproduce this... on MC 1.21.0. meanwhile 1.21.1 and 1.20.6 both work for me. I don't develop for 1.21.0 anymore cause 1.21.1 didn't change anything related to recipes (or so I thought), but I'll see if there's an easy solution for this or not that continues to work without me needing a separate jar file for 1.21.0.

**Comment by Builderb0y** [comment] 2024-10-01 23:23
Turns out this was caused by something completely unrelated to recipes, but it was in my own code, so that'll be fixed *again* in the next version.

**Comment by Builderb0y** [comment] 2024-10-02 03:51
Should hopefully be fixed for real this time in V4.4.1.

**Closed as completed by Builderb0y** 2024-10-02 03:51 UTC

**Comment by st4nley29** [comment] 2024-10-02 10:53
i appreciate your work, mate
