### ISSUE TITLE
Big Globe-4.6.0-MC1.20.1 Failed to start the fresh (no mods) minecraft server

### ISSUE THREAD

**Issue by AmeriBaha** [Builderb0y/BigGlobe#68] opened 2024-11-15 02:58 UTC
I have a small Fabric 1.20.1 server that runs perfectly with version 4.5.0 and when I tried to install the update and even make a "new" server I got this error message every time.

`[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bigglobe' at 'builderb0y.bigglobe.BigGlobeMod'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
        at builderb0y.bigglobe.entities.BigGlobeEntityTypes.<clinit>(BigGlobeEntityTypes.java:54) ~[Big%20Globe-4.6.0-MC1.20.1.jar:?]
        at builderb0y.bigglobe.BigGlobeMod.onInitialize(BigGlobeMod.java:93) ~[Big%20Globe-4.6.0-MC1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at builderb0y.bigglobe.entities.BigGlobeEntityTypes.<clinit>(BigGlobeEntityTypes.java:54) ~[Big%20Globe-4.6.0-MC1.20.1.jar:?]
        at builderb0y.bigglobe.BigGlobeMod.onInitialize(BigGlobeMod.java:93) ~[Big%20Globe-4.6.0-MC1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
`

I wanted to notify you of the error and thank you again for your work. ^^

**Comment by Builderb0y** [comment] 2024-11-15 05:21
Known. Will be fixed in the next version.

**Comment by AmeriBaha** [comment] 2024-11-15 05:23
Thx ^^

**Comment by UnknowUser0** [comment] 2024-11-17 14:53
this is also problematic on version Big Globe-4.6.0-MC1.21.3

**Comment by yeet-dot-org** [comment] 2024-11-17 22:45
> Known. Will be fixed in the next version.

on a similar note, when I run it on my fabric server (I found out a paper mc server I something different) I get the same error message plus some more dependencies mods that I wasn't aware I needed that were missing, see the log below for what I'm talking about:


C:\Users\adkar\Downloads\fabric-server-mc.1.21.3>java -Xmx10G -jar fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[15:29:36] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.9
[15:29:36] [main/WARN]: Warnings were found!
 - Mod 'Big Globe' (bigglobe) 4.6.0 recommends any version of satin, which is missing!
         - You should install any version of satin for the optimal experience.
[15:29:36] [main/INFO]: Loading 43 mods:
        - bigglobe 4.6.0
           \-- builderb0y_autocodec 5.0.0
        - fabric-api 0.108.0+1.21.3
           |-- fabric-api-base 0.4.49+fd37071f40
           |-- fabric-api-lookup-api-v1 1.6.80+fd37071f40
           |-- fabric-biome-api-v1 14.0.6+fd37071f40
           |-- fabric-block-api-v1 1.0.28+fd37071f40
           |-- fabric-block-view-api-v2 1.0.16+fd37071f40
           |-- fabric-blockrenderlayer-v1 2.0.3+fd37071f40
           |-- fabric-client-tags-api-v1 1.1.23+fd37071f40
           |-- fabric-command-api-v1 1.2.57+f71b366f40
           |-- fabric-command-api-v2 2.2.36+fd37071f40
           |-- fabric-commands-v0 0.2.74+df3654b340
           |-- fabric-content-registries-v0 9.1.7+fd37071f40
           |-- fabric-convention-tags-v1 2.1.2+7f945d5b40
           |-- fabric-convention-tags-v2 2.9.2+84ebbb0e40
           |-- fabric-crash-report-info-v1 0.3.3+fd37071f40
           |-- fabric-data-attachment-api-v1 1.3.0+e9d2cfc840
           |-- fabric-data-generation-api-v1 21.0.16+fd37071f40
           |-- fabric-dimensions-v1 4.0.7+fd37071f40
           |-- fabric-entity-events-v1 2.0.7+825023f840
           |-- fabric-events-interaction-v0 2.0.11+c2c3ac4740
           |-- fabric-game-rule-api-v1 1.0.59+fd37071f40
           |-- fabric-item-api-v1 11.1.6+fd37071f40
           |-- fabric-item-group-api-v1 4.1.16+fd37071f40
           |-- fabric-key-binding-api-v1 1.0.53+fd37071f40
           |-- fabric-keybindings-v0 0.2.51+df3654b340
           |-- fabric-lifecycle-events-v1 2.5.0+6da5ef6940
           |-- fabric-loot-api-v2 3.0.25+3f89f5a540
           |-- fabric-loot-api-v3 1.0.13+fd37071f40
           |-- fabric-message-api-v1 6.0.20+fd37071f40
           |-- fabric-model-loading-api-v1 3.0.8+fd37071f40
           |-- fabric-networking-api-v1 4.3.4+fd37071f40
           |-- fabric-object-builder-api-v1 17.0.8+fd37071f40
           |-- fabric-particles-v1 4.0.9+fd37071f40
           |-- fabric-recipe-api-v1 7.0.3+fd37071f40
           |-- fabric-registry-sync-v0 5.2.1+fd37071f40
           |-- fabric-renderer-api-v1 4.0.4+fd37071f40
           |-- fabric-renderer-indigo 1.9.4+fd37071f40
           |-- fabric-rendering-data-attachment-v1 0.3.54+73761d2e40
           |-- fabric-rendering-fluids-v1 3.1.14+fd37071f40
           |-- fabric-rendering-v0 1.1.82+df3654b340
           |-- fabric-rendering-v1 8.0.6+fd37071f40
           |-- fabric-resource-conditions-api-v1 5.0.8+fd37071f40
           |-- fabric-resource-loader-v0 3.0.6+fd37071f40
           |-- fabric-screen-api-v1 2.0.33+fd37071f40
           |-- fabric-screen-handler-api-v1 1.3.99+fd37071f40
           |-- fabric-sound-api-v1 1.0.29+fd37071f40
           |-- fabric-transfer-api-v1 5.4.2+fd37071f40
           \-- fabric-transitive-access-wideners-v1 6.1.8+fd37071f40
        - fabricloader 0.16.9
           \-- mixinextras 0.4.1
        - java 21
        - minecraft 1.21.3
[15:29:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/adkar/Downloads/fabric-server-mc.1.21.3/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[15:29:36] [main/INFO]: Compatibility level set to JAVA_17
[15:29:36] [main/INFO]: Compatibility level set to JAVA_21
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.BigGlobeConfig_ImplementConfigData because required mod cloth-config is absent.
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.DhScriptedWorldGenerator_BackwardsCompatibility because required mod distanthorizons is absent.
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.ImmersivePortals_NetherPortalMatcher_PlacePortalHigherInBigGlobeWorlds because required mod imm_ptl_core is absent.
[15:29:37] [main/INFO]: Applying mixin builderb0y.bigglobe.mixins.MobSpawnerLogic_SpawnLightning because incompatible mod connector is absent.
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.Voxy_ContextSelectionSystem_UseMemoryStorageBackendForDebugging because required mod voxy is absent.
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.Voxy_WorldEngine_UseBigGlobeGenerator because required mod voxy is absent.
[15:29:37] [main/INFO]: Not applying mixin builderb0y.bigglobe.mixins.Voxy_WorldSection_DataGetter because required mod voxy is absent.
[15:29:37] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[15:29:47] [main/INFO]: Initializing...
[15:29:47] [main/INFO]: Failed to register ConfigSerializer. Cloth Config is probably not installed.
[15:29:48] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bigglobe' at 'builderb0y.bigglobe.BigGlobeMod'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
        at knot/builderb0y.bigglobe.entities.BigGlobeEntityTypes.<clinit>(BigGlobeEntityTypes.java:54) ~[Big%20Globe-4.6.0-MC1.21.3.jar:?]
        at knot/builderb0y.bigglobe.BigGlobeMod.onInitialize(BigGlobeMod.java:93) ~[Big%20Globe-4.6.0-MC1.21.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/builderb0y.bigglobe.entities.BigGlobeEntityTypes.<clinit>(BigGlobeEntityTypes.java:54) ~[Big%20Globe-4.6.0-MC1.21.3.jar:?]
        at knot/builderb0y.bigglobe.BigGlobeMod.onInitialize(BigGlobeMod.java:93) ~[Big%20Globe-4.6.0-MC1.21.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more

C:\Users\adkar\Downloads\fabric-server-mc.1.21.3>PAUSE
Press any key to continue . . .

**Comment by Builderb0y** [comment] 2024-11-17 23:23
That's the same error, and nothing else in that log is noteworthy. Big globe doesn't have any required dependencies besides fabric API, but it does have integration with several other mods. The integration code is automatic and disables itself if those mods are absent.

**Comment by yeet-dot-org** [comment] 2024-11-18 03:04
> That's the same error, and nothing else in that log is noteworthy. Big globe doesn't have any required dependencies besides fabric API, but it does have integration with several other mods. The integration code is automatic and disables itself if those mods are absent.

Ah, I had no idea there was integration with immersive portals and other mods (also according to the log, the satin API mod is recommended to use I guess), I'll wait for the next version then. By the way if a person joins the server without the distant horizons mod (basically vanilla) when the server has distant horizons enabled, will they be able to join?

**Comment by Builderb0y** [comment] 2024-11-18 03:51
> also according to the log, the satin API mod is recommended to use I guess

Only on clients. Satin API will do nothing (or possibly crash) on servers.

> By the way if a person joins the server without the distant horizons mod (basically vanilla) when the server has distant horizons enabled, will they be able to join?

I would assume so? Distant horizons isn't my mod though, so I'm not sure why you're asking me this question.

**Comment by Builderb0y** [comment] 2024-11-19 00:02
The next version has now been released, so hopefully dedicated servers work correctly now.

**Closed as completed by Builderb0y** 2024-11-19 00:02 UTC

**Comment by yeet-dot-org** [comment] 2024-11-22 23:57
> The next version has now been released, so hopefully dedicated servers work correctly now.

btw, what distant horizon mod version  should i use?   (jar.)

**Comment by Builderb0y** [comment] 2024-11-23 01:19
Any version that works. If more than one version works, go with the latest of the working versions. Same as any other mod.
