### ISSUE TITLE
Voxy integration problems

### ISSUE THREAD

**Issue by alexander4308** [Builderb0y/BigGlobe#10] opened 2024-09-11 10:11 UTC
1. All distant water is black around the camera.
![{3E41EE8A-F9DB-4765-B083-8A3C0AED030F}](https://github.com/user-attachments/assets/a1080c7f-d80f-4dec-86af-89f863eaf0fe)

2. Turning off "Skip Underground" option causing this exception:
```
[10:08:37] [Big Globe Worker Thread/INFO]: [System] [CHAT] [Big Globe/Scripting]: Caught exception from builderb0y.bigglobe.chunkgen.scripted.SurfaceScript$Holder: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26215()" because "state" is null; Check your logs for more info.
[10:08:37] [Big Globe Worker Thread/ERROR]: Script source was:
1:	int surfaceY = ceilInt(`bigglobe:overworld/processed_surface_y`)
2:	;skip the bulk of the work if the surface is outside the world height,
3:	;which could happen with cubic chunks.
4:	if (surfaceY.isBetween[minY, maxY]:
5:	long seed = columnSeed(16x89EA3521C6A72ABCUL)
6:	double slopeSquared = (
7:	+ dx(`bigglobe:overworld/basic_surface_y`) ^ 2
8:	+ dz(`bigglobe:overworld/basic_surface_y`) ^ 2
9:	)
10:	if ((seed := seed.newSeed()).nextDouble() < unmixSmooth(8.0L, 4.0L, `bigglobe:overworld/processed_surface_y`):
11:	int depth = (seed := seed.newSeed()).nextInt(3, 7)
12:	setBlockStates(surfaceY - depth, surfaceY, 'minecraft:gravel')
13:	)
14:	if (`bigglobe:overworld/lake_surface_states` != null:
15:	setBlockStates(
16:	surfaceY - (seed := seed.newSeed()).nextInt(3, 7),
17:	surfaceY,
18:	`bigglobe:overworld/lake_surface_states`.under
19:	)
20:	)
21:	int depth = floorInt(
22:	+ (seed := seed.newSeed()).nextDouble(3.0L, 7.0L) ;base randomness
23:	- (slopeSquared * 3.0L) ;less depth when slope is high
24:	+ (`bigglobe:overworld/height_adjusted_foliage`(surfaceY) * 2.0L)
25:	)
26:	if (depth > 0:
27:	if (`bigglobe:overworld/lake_surface_states` != null:
28:	setBlockStates(
29:	surfaceY - depth,
30:	surfaceY,
31:	`bigglobe:overworld/lake_surface_states`.top
32:	)
33:	)
34:	else (
35:	SurfaceStates states = `bigglobe:overworld/surface_states`
36:	boolean hadBlock = false
37:	for (int y in -range[surfaceY - depth, surfaceY):
38:	hadBlock = (getBlockState(y) !=. 'minecraft:air').if (
39:	setBlockState(y, hadBlock ? states.subsurfaceState : states.surfaceState)
40:	)
41:	)
42:	)
43:	)
44:	if (`bigglobe:overworld/processed_surface_y` > `bigglobe:overworld/sea_level` && (seed := seed.newSeed()).nextFloat() < `bigglobe:overworld/snow_chance`:
45:	int snowStart = surfaceY
46:	while (snowStart > minY && getBlockState(snowStart - 1).isAir(): --snowStart)
47:	int snowEnd = lowerInt(`bigglobe:overworld/snow_y`)
48:	if (snowEnd >= snowStart:
49:	setBlockStates(snowStart, snowEnd, 'minecraft:snow[layers=8]')
50:	int remaining = floorInt((`bigglobe:overworld/snow_y` % 1.0I) * 8.0I)
51:	if (snowStart == snowEnd: remaining = max(remaining, 1))
52:	if (remaining != 0:
53:	setBlockState(snowEnd, BlockState('minecraft:snow', layers: remaining))
54:	)
55:	)
56:	else (
57:	setBlockState(snowStart, 'minecraft:snow[layers=1]')
58:	)
59:	)
60:	)

[10:08:37] [Big Globe Worker Thread/ERROR]: Exception was: 
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26215()" because "state" is null
	at builderb0y.bigglobe.scripting.wrappers.BlockStateWrapper.isAir(BlockStateWrapper.java:98) ~[Big%20Globe-4.3.2-MC1.21.1.jar:?]
	at builderb0y.bigglobe.chunkgen.scripted.SurfaceScript$Generated_678.generateSurface(Script:46) ~[?:?]
	at builderb0y.bigglobe.chunkgen.scripted.SurfaceScript$Generated_678.generateSurface(Script) ~[?:?]
	at builderb0y.bigglobe.chunkgen.scripted.SurfaceScript$Holder.generateSurface(SurfaceScript.java:157) ~[Big%20Globe-4.3.2-MC1.21.1.jar:?]
	at builderb0y.bigglobe.chunkgen.scripted.Layer.emitSegments(Layer.java:62) ~[Big%20Globe-4.3.2-MC1.21.1.jar:?]
	at builderb0y.bigglobe.chunkgen.scripted.Layer.emitSegments(Layer.java:55) ~[Big%20Globe-4.3.2-MC1.21.1.jar:?]
	at builderb0y.bigglobe.compat.voxy.VoxyWorldGenerator.lambda$createChunk$0(VoxyWorldGenerator.java:57) ~[Big%20Globe-4.3.2-MC1.21.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
```

**Comment by alexander4308** [comment] 2024-09-11 10:17
Mod list:
```
Big Globe 4.3.2
Fabric API 0.104.0+1.21.1
Freecam (Modrinth Edition) 1.3.0+mc1.21
Mod Menu 11.0.2
Nvidium 0.3.1-17bbd38 (self-built from source on sodium-0.5 branch)
voxy 0.1.6 (self-built from source)
Sodium 0.5.11+mc1.21
Sodium Extra 0.5.7+mc1.21
```

**Comment by Builderb0y** [comment] 2024-09-13 04:50
The black water bug is caused by incorrect light levels. Next version will contain a fix for this, as well as a new config option to fix the remaining (rarer) lighting issues at the cost of slower generation. In the meantime, you can also work around it with nightvision.

The exception is probably caused by a particularly big cave intersecting the surface. Snow tried to generate down to the bottom of the cave, only to find that the cave goes past the generated Y range because I used the wrong flag for determining what that Y range should be. This will be fixed in the next version too.

**Comment by alexander4308** [comment] 2024-09-13 11:12
Another bug when you install mod on server and try to join with Voxy, the game flooded with logs.
![image](https://github.com/user-attachments/assets/c5404c38-023a-4507-b109-1a1010920766)

**Comment by Builderb0y** [comment] 2024-09-13 18:30
Oh yeah, I found that out last night too. It also happens when traveling to hyperspace in singleplayer. I'll be releasing a fix for that in the next version too. Hopefully soon.

**Comment by Builderb0y** [comment] 2024-09-14 22:58
These issues should be fixed in V4.3.3.

**Closed as completed by Builderb0y** 2024-09-14 22:58 UTC

**Comment by alexander4308** [comment] 2024-09-26 16:08
I would like to ask do not override featured LOD's with terrain prediction, fix biome colours and use 4 light level for skylands.

**Comment by Builderb0y** [comment] 2024-09-26 17:03
I'm not sure what you mean by "featured LODs". I generate a simplified version of terrain anywhere Voxy has no data. Biome colors cannot be fixed in the current version of Voxy due to technical limitations in how Voxy works. Future versions of Voxy might improve this. In the meantime, Distant Horizons does not have this technical limitation, and foliage colors work correctly there. Light level 4 under skylands would not mimic how light normally propagates in vanilla minecraft, though I do agree this is one of a few situations where vanilla lighting looks really bad in big globe.
